### ISSUE TITLE
Checklist about Grasshopper releases

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-grasshopper#8]
@ish-hcc (cc. @yunkon-kim @sykim-etri @dev4unet)

안녕하세요.

📅 Grasshopper v0.2.x릴리스 일정을 11/15(금)로 계획하고 있습니다.

현재, SW 마이그레이션은 기능 개발, 테스트 및 통합을 중심으로 추진하기로 협의된 바가 있습니다. 제 생각에는 Cicada 까지 통합 및 테스트되면 될 것 같습니다. 

🙋 먼저, 관련하여 이슈가 있으신 경우 댓글로 남겨주시기 바랍니다.

올해 목표치에 이슈가 없을지 확인 부탁드리며, 일정 조율, 타 서브시스템의 기능/API 개선 등이 필요하시면 답글로 남겨주십시오.

☑️ 아래 사항들에 대해 추진을 부탁드리며, 완료된 항목들은 Checked 처리하여 주십시오.
* [x] Grasshopper 개발 및 테스트
* [x] Grasshopper 관련 서브시스템과 통합 테스트 ([Sequence Diagram](https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md) 참고 및 개선)
* [x] Grasshopper 실행 지원
* [x] Grasshopper 문서화
* [x] Grasshopper  릴리스
각 항목별 자세한 사항은 아래 링크의 "저장소별 추진사항"을 참고하시면 될 것 같습니다.
Ref: https://github.com/cloud-barista/cloud-migrator/issues/11

릴리스 이후 Cicada에서 통합 및 테스트 진행해 주시면 될 것 같습니다.

(참고)
이번 Cloud-Migrator v0.3.0 통합 및 릴리스는 두 가지 측면에서 진행됩니다.

* 컴퓨팅 인프라 마이그레이션: Cloud-Migration portal에서 3종 클라우드로, 3종 자원에 대해 마이그레이션을 수행할 수 있어야 함
* SW 마이그레이션: 기능 개발, 테스트 및 통합 추진 (portal 통합 대상 X)

**Comment by ish-hcc** [comment]
@yunkon-kim 
진행 상황 먼저 말씀드립니다.
현재 nginx 온프레미스 서버 대상으로 Tumblebug로 배포된 VM에 수동으로 마이그레이션 요청시
nginx 설치 -> Config 파일들 마이그레이션 -> 서비스 상태 마이그레이션 -> 서비스 상태 검증 -> 서비스 사용 리슨 포트 사용 검증
순으로 진행되어 nginx의 수동 마이그레이션은 정상 동작이 확인되었습니다.

현재 진행중인 사항들입니다.
- NFS 온프레미스 서버 대상의 테스트 진행
- Source Group ID 제공시 서버별 마이그레이션 가능한 소프트웨어 목록 제공 기능

이 두가지가 완료되면 Sequence Diagram 및 문서화가 가능해 질 것 같습니다.

- Kubernetes 및 컨테이너 마이그레이션은 차주에 진행이 되어야 할 것 같습니다.
감사합니다.

**Comment by yunkon-kim** [comment]
@ish-hcc 현황 공유 감사합니다!

SW 마이그레이션과 관련해서는 일정을 조율할 수 있는 상황입니다. Grasshopper릴리스, Grasshopper-Cicada간 통합 및 테스트는 **별도의 일정으로 추진**해 주시면 될 것 같습니다. 

관련하여,
1. 대략적인 추진 일정을 공유 바랍니다. 
2. 11/20(수)에 예정된 Cicada 릴리스 일정은 컴퓨팅 인프라 중심으로 추진하여 주십시오.
